# Generated by Django 2.0.2 on 2018-03-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180312_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField()),
                ('tags', models.ManyToManyField(blank=True, related_name='_tag_tags_+', to='books.Tag', verbose_name='tags')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_book_tags_+', to='books.Tag', verbose_name='tags'),
        ),
    ]
