# Generated by Django 2.0.2 on 2018-03-16 16:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '__first__'),
        ('meta_info', '0001_initial'),
        ('books', '0010_auto_20180313_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('page', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('progress', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('copy', models.TextField(blank=True, db_index=True, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='book',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.RemoveField(
            model_name='readinglist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='readinglist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='copy',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='book',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_book_tags_+', to='meta_info.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ReadingList',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='bookreview',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='books.Book', verbose_name='Book reviews'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile.Profile'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='progress',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='review', to='books.BookProgress', verbose_name='Book review Progress'),
        ),
        migrations.AddField(
            model_name='bookreview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_bookreview_tags_+', to='meta_info.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='book',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='progress+', to='books.Book', verbose_name='Book progress'),
        ),
        migrations.AddField(
            model_name='bookprogress',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='profile.Profile'),
        ),
    ]
