# Generated by Django 2.0.2 on 2018-04-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='reading_list',
            field=models.ManyToManyField(blank=True, related_name='circles', to='books.ReadingList', verbose_name='Reading List'),
        ),
    ]
