# Generated by Django 2.0.2 on 2018-03-16 16:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('copy', models.TextField(blank=True, db_index=True, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('slug_u', models.SlugField()),
                ('copy', models.CharField(db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='_tag_tags_+', to='meta_info.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='metainfo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='_metainfo_tags_+', to='meta_info.Tag', verbose_name='Tags'),
        ),
    ]
