# Generated by Django 2.0.2 on 2018-03-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SMS Alerts', max_length=50)),
                ('send_alert', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
